### PR TITLE
feat(facelist): Allow .com tink address

### PR DESCRIPTION
**Pull request by woodenflute**
### Why
More and more new colleagues are defaulting to @tink.com as their email. 
### What
This change filters for both @tink.se and @tink.com.

### CODE REVIEW

**Comment by vrklgn** [comment]
I can scrap mine 😂 - I just guess-worked how golang works, this looks way cleaner!

**Review by ahilsend — APPROVED** [review]

**Comment by woodenflute** [comment]
@vrklgn Honestly I think it was good though. It was the simplest possible change 🙂
bors r+

**Comment by ahilsend** [comment]
looks like there's no bors here :sweat_smile:

**Comment by woodenflute** [comment]
Thanks!

**Pull request merged**
