### PR TITLE
fixes: close fd, fmt, lint

### PR DESCRIPTION
**Pull request by hashier**
Fix some random stuff, see commit messages for more information

### CODE REVIEW

**Comment by hashier** [comment]
No merge rights \:

**Comment by ahilsend** [comment]
there is no bors here :upside_down_face:

**Comment by ahilsend** [comment]
and I don't know how to deploy this thing

**Comment by hashier** [comment]
cc: @cholmboe

**Comment by cholmboe** [comment]
Thank you for the pr @hashier! ...and sorry for not noticing the pr for a month(!) :)

**Comment by hashier** [comment]
Thanks! Happy to now being a proud contributor to this fantastic project <3

**Pull request merged**
